apiVersion: components.blocc.dev/v1beta1
kind: Backend
metadata:
  name: server
spec:
  resourceProfiles:
    large:
      replicas: 1
      size:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 150m
          memory: 250Mi
    small:
      replicas: 1
      size:
        requests:
          cpu: 20m
          memory: 100Mi
  build:
    dockerfile: Dockerfile
    context: ../../

  ports:
    internal: 3000

